EXP_NAME: "Default Experiment"
EXP_DESC: "Default Experiment Description"

MODE: MARK
MODEL:
  FE_HIDDEN: 32
  EMBED_DIM: 128
  DIMENSIONS: [64, 128, 256]

DATASET:
  NAME: Cifar100
  NUM_CLASSES: 5
  NUM_TASKS: 20

TRAINING:
  LR: 
    FE: 1e-1
    INIT_KB: 1e-1
    MG_N_C: 1e-1
    FINETUNE_MG_N_C: 2e-5

  EPOCHS:
    FE: 50
    INIT_KB: 50
    MG_N_C: 50
    FINETUNE_MG_N_C: 40
  
  BATCH_SIZE: 128